// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvmEuOjPjRsZk7uPi8EAKPID82G1MAfgI',
    appId: '1:499218687651:web:379f259d25a4d75fbd4116',
    messagingSenderId: '499218687651',
    projectId: 'grocery-store-3d0ba',
    authDomain: 'grocery-store-3d0ba.firebaseapp.com',
    storageBucket: 'grocery-store-3d0ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqecmCnScVnEpLNGk0P3CCN6MCX1huG5s',
    appId: '1:499218687651:android:0fe8c1d32caaa4b5bd4116',
    messagingSenderId: '499218687651',
    projectId: 'grocery-store-3d0ba',
    storageBucket: 'grocery-store-3d0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrVqjfwDlITNf__suX_r6cVplP9Jj5z0',
    appId: '1:499218687651:ios:d24627a1076f57cebd4116',
    messagingSenderId: '499218687651',
    projectId: 'grocery-store-3d0ba',
    storageBucket: 'grocery-store-3d0ba.appspot.com',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrVqjfwDlITNf__suX_r6cVplP9Jj5z0',
    appId: '1:499218687651:ios:d24627a1076f57cebd4116',
    messagingSenderId: '499218687651',
    projectId: 'grocery-store-3d0ba',
    storageBucket: 'grocery-store-3d0ba.appspot.com',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvmEuOjPjRsZk7uPi8EAKPID82G1MAfgI',
    appId: '1:499218687651:web:8f7576ed2d1ecc59bd4116',
    messagingSenderId: '499218687651',
    projectId: 'grocery-store-3d0ba',
    authDomain: 'grocery-store-3d0ba.firebaseapp.com',
    storageBucket: 'grocery-store-3d0ba.appspot.com',
  );

}